version: '3.8'
services:
 db:
  #build: ./src/prisma-db
  image: postgres:16.2-alpine3.18
  #app/db
  container_name: ${POSTGRES_CONTAINER}
  environment:
   - POSTGRES_PORT=${POSTGRES_PORT}
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   #- POSTGRES_DB=${POSTGRES_DB}
   #- POSTGRES_CONTAINER=${POSTGRES_CONTAINER}
  ports:
   - ${POSTGRES_PORT}:5432
  volumes:
   - db-data:/var/lib/postgresql/data
   - db-logs:/var/log/postgresql
  restart: always

  # networks:
  # - my-network

volumes:
  db-data:
  db-logs:


# networks:
#   my-network: 
#     driver: bridge